# Generated by Django 5.1.4 on 2025-01-13 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0003_projectrole_projectmembership'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('priority', models.CharField(choices=[('Highest_Priority', 'Highest Priority'), ('Lowest_Priority', 'Lowest Priority')], max_length=20)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.employeeprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project.project')),
            ],
        ),
    ]
