# Generated by Django 5.1.4 on 2025-01-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'Todo'), ('IN PROGRESS', 'In Progress'), ('IN REVIEW', 'In Review'), ('DONE', 'Done')], default='TODO', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('Highest_Priority', 'Highest Priority'), ('Lowest_Priority', 'Lowest Priority')], max_length=20, null=True),
        ),
    ]
