# Generated by Django 5.1.4 on 2025-01-15 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_status_alter_task_priority'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='task.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.employeeprofile')),
            ],
        ),
    ]
